global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:5000']
    
  - job_name: 'analyzer'
    static_configs:
      - targets: ['analyzer:5001']
    
  - job_name: 'manager'
    static_configs:
      - targets: ['manager:5002']
    
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']